### PR TITLE
Notes button

### PR DESCRIPTION
**Pull request by willemvb**
- Use notes count as button
- Add close button on `NotesPane`
- Add `notes` prop to `Wires`
- Small z-index issue on `Toolbar`

### CODE REVIEW

**Comment by sebastiandedeyne** [comment]
Looks good to me, although I thought of an edge case: Sometimes I don't provide `pages` when I'm making a prototype for a single page. Where would we display the note count & toggle in that case?

**Comment by willemvb** [comment]
Display it stand-alone in the bottom-right corner?

**Comment by sebastiandedeyne** [comment]
Sounds good!

**Comment by willemvb** [comment]
Should be available in https://github.com/spatie/wires/pull/11/commits/d173cd0c8a98f99c20dc700ecd0b0e02566c3b3c

**Pull request merged**
